= Homework Concurrency

== Project `File Util`

Отдельным `private` методом сделан метод который осуществляет чтение файла и возвращает объект `StringBuilder`. Он используется во ВСЕХ методах класса `FileUtil` Метод имеет следующий код:

----
private StringBuilder read(String source) {
        StringBuilder builder = new StringBuilder();

        try (BufferedReader reader = new BufferedReader(new FileReader(source))) {
            String line;

            while ((line = reader.readLine()) != null) {
                builder.append(line).append("\n");
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        return builder;
}
----

=== Task 1

Метод `copyContentInUpperReg(String source, String destination)` переписывает содержимое одного файла в другой файл, но только в верхнем регистре. Где *source* - путь к исходному файлу, а *destination* - путь к результирующему файлу.

=== Task 2

Метод `listOfStrings(String source)`, который принимает путь к файлу и возвращает список строк этого файла. Где *source* - путь к исходному файлу.

=== Task 3

Метод `listOfStrings(String source)`, возвращает список слов начинающихся с гласной буквы. Где *source* - путь к исходному файлу.

=== Task 4

Метод `listOfCoincidences(String source)`, возвращает список слов, для которых последняя буква совпадает с первой буквой следующего за ним слова. Где *source* - путь к исходному файлу.

=== Task 5

Реализовать метод, который принимает путь к файлу. Метод возвращает список наибольшей комбинации цифр для каждой строки, которые идут в порядке возрастания.

Например:

Input:

----
1 2 1 2 3
67 68 69 23
----

Output:
----
"1 2 3", "67 68 69"
----

=== Task 6

Реализовать метод, который принимает путь к файлу. Метод возвращает частоту повторяемости всех букв в тексте, игнорируя регистр.

=== Task 7

Реализовать метод, который принимает путь к файлу. Метод возвращает частоту повторяемости всех слов в тексте в порядке возрастания частоты повторяемости.

=== Task 8

Реализовать метод, который принимает путь к файлу с целыми числами и сортирующий содержимое файла по возрастанию и сохраняющий результат в файл `$++{origin_filepath}++_`.

=== Task 9

Реализовать метод, который принимает путь к файлу, где содержится фамилия студентов и их оценки (в качестве разделителя используется `,`) и возвращает успеваемость студентов.

=== Task 10

Реализовать метод, который принимает путь к файлу с java кодом, и 2 модификатора доступа в виде строки и заменяет все модификаторы доступа `X` в объявлении атрибутов и методов класса на `Y` и сохраняющий результат в файл `$++{origin_filepath}++_`.