= Homework Lambda Expressions

== Task 1, 2

Поток *Producer* бесконечно считывает целые числа, которые пользователь вводит в *Standard Input*. После ввода сохраняет целые числа в *Queue*. При вводе `-1` поток *Producer* завершает свою работу. Поток *Producer* реализован в пакете `.jobs` классом `CopyJob` с имплементацией интерфейса `Runnable`.

== Project 'Math’s statistics'

Если пользователь вводит некорректные данные, то поток *Producer* бросает исключение `UserInputException`, но при этом продолжает работать. `UserInputException` является custom исключением, реализованным в классе `UserInputException` в пакете `.exceptions` расширяя класс `Exceptions`.

== Project 'City Helper'

Поток *Consumer*, который забирает числа из *Queue* и засыпает на количество секунд равное этому числу. При этом засыпание потока *Consumer* происходит в том порядке, в котором значения целых чисел были введены пользователем. Поток *Consumer* реализован как класс `ConsumerJob` имплементирующий интерфейса `Runnable` в пакете `.jobs`.

Для реализации и улучшения читаемости когда задачи по записи в *File*: `$+{timestamp}+ - $+{thread-name}+ - I slept $+{seconds}+ seconds` и `$+{timestamp}+ - $+{thread-name}+ - ...` были вынесены в отдельный класс-утилиту `FileUtil` находящийся в пакете `.utils`. Методы из `FileUtil` использованы в `ConsumerJob`.

== Project 'TV'

Возможность добавления нескольких потоков *Consumer* и конфигурации их количества реализованы в конфигурационном классе `ThreadConfig` в пакете `.config`.