= Homework Lambda Expressions

== Task 1, 2

=== Task 1

* Метод `getArguments(String[] strings)` принимает массив строк и возвращающает `Map`, где `key` - название аргумента, `value` - значение аргумента
* Метод convert(Map<String, String> map) конвертирует `Map` с аргументами и их значениями в массив строк

=== Task 2

* Метод в 1 столбец таблицу умножения от 1 до 10
* Метод в 5 столбцов таблицу умножения от 1 до 10

== Project 'Math’s statistics'

Если пользователь вводит некорректные данные, то поток *Producer* бросает исключение `UserInputException`, но при этом продолжает работать. `UserInputException` является custom исключением, реализованным в классе `UserInputException` в пакете `.exceptions` расширяя класс `Exceptions`.

== Project 'City Helper'

Поток *Consumer*, который забирает числа из *Queue* и засыпает на количество секунд равное этому числу. При этом засыпание потока *Consumer* происходит в том порядке, в котором значения целых чисел были введены пользователем. Поток *Consumer* реализован как класс `ConsumerJob` имплементирующий интерфейса `Runnable` в пакете `.jobs`.

Для реализации и улучшения читаемости когда задачи по записи в *File*: `$+{timestamp}+ - $+{thread-name}+ - I slept $+{seconds}+ seconds` и `$+{timestamp}+ - $+{thread-name}+ - ...` были вынесены в отдельный класс-утилиту `FileUtil` находящийся в пакете `.utils`. Методы из `FileUtil` использованы в `ConsumerJob`.

== Project 'TV'

Возможность добавления нескольких потоков *Consumer* и конфигурации их количества реализованы в конфигурационном классе `ThreadConfig` в пакете `.config`.