= Homework Lambda Expressions

== Task 1, 2

=== Task 1

Задание выполнено в классе `Arguments`.

* Статический метод `getArguments(String[] strings)` принимает массив строк и возвращающает `Map`, где `key` - название аргумента, `value` - значение аргумента
* Статический метод convert(Map<String, String> map) конвертирует `Map` с аргументами и их значениями в массив строк

=== Task 2

Задание выполнено в классе `MultiplicationTable`.

* Статический метод `tableOut()` выводит в консоль таблицу умножения от 1 до 10 в 1 столбец

== Project 'Math’s statistics'

Utility class `MathStatUtil`, который реализует следующие методы:

* Метод `generate()` генерация набора случайных целых чисел
* Подсчет количества:
** Метод `count(int[] numbers, Params params)` реализует счёт четных, нечетных, равных 0, выбор счёта осуществляется с помощью Enum Params, передачей в метод `EVEN`, `ODD`, `ZERO_EQUALS` соответственно.
** Метод `count(int[] numbers, int someValue)` реализует счёт чисел равных некоторому значению

== Project 'City Helper'

Поток *Consumer*, который забирает числа из *Queue* и засыпает на количество секунд равное этому числу. При этом засыпание потока *Consumer* происходит в том порядке, в котором значения целых чисел были введены пользователем. Поток *Consumer* реализован как класс `ConsumerJob` имплементирующий интерфейса `Runnable` в пакете `.jobs`.

Для реализации и улучшения читаемости когда задачи по записи в *File*: `$+{timestamp}+ - $+{thread-name}+ - I slept $+{seconds}+ seconds` и `$+{timestamp}+ - $+{thread-name}+ - ...` были вынесены в отдельный класс-утилиту `FileUtil` находящийся в пакете `.utils`. Методы из `FileUtil` использованы в `ConsumerJob`.

== Project 'TV'

Возможность добавления нескольких потоков *Consumer* и конфигурации их количества реализованы в конфигурационном классе `ThreadConfig` в пакете `.config`.