= Homework Lambda Expressions

== Task 1, 2

=== Task 1

Задание выполнено в классе `Arguments`.

* Статический метод `getArguments(String[] strings)` принимает массив строк и возвращающает `Map`, где `key` - название аргумента, `value` - значение аргумента
* Статический метод convert(Map<String, String> map) конвертирует `Map` с аргументами и их значениями в массив строк

=== Task 2

Задание выполнено в классе `MultiplicationTable`.

* Статический метод `tableOut()` выводит в консоль таблицу умножения от 1 до 10 в 1 столбец

== Project 'Math’s statistics'

Utility class `MathStatUtil`, который реализует следующие методы:

* Метод `generate()` генерация набора случайных целых чисел
* Подсчет количества:
** Метод `count(int[] numbers, Params params)` реализует счёт четных, нечетных, равных 0, выбор счёта осуществляется с помощью Enum Params, передачей в метод `EVEN`, `ODD`, `ZERO_EQUALS` соответственно.
** Метод `count(int[] numbers, int someValue)` реализует счёт чисел равных некоторому значению

== Project 'City Helper'

Utility class `CityHelpUtil`, реализует следующие методы:

* Метод `getCities(List<String> list, Params params)` реализует получение городов исходя из параметра params, выбор осуществляется из Enum Params:
** Уникальных с параметром `UNIQUE`
** С названием, которое длиннее шесть символов с параметром `NAME_LONGER_THAN_6`
* Метод `getCities(List<String> list, char startsFromChar)` получение городов начинающихся на заданную букву
* Метод `count(List<String> list, String cityToCount)` получение количества употребления конкретного города в списке

== Project 'TV'

Utility class `TVUtil`, реализует следующие методы:

* получение телевизоров:
** с заданной диагональю
** какого-то производителя
** не старше какого-то года
** с ценой в каком-то диапазоне
** отсортированные по цене (по возрастанию)
** отсортированные по цене (по убыванию)
** отсортированные по диагонали (по возрастанию)
** отсортированные по диагонали (по убыванию)